/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AscendReaderRouteImport } from './routes/ascend.reader'
import { Route as AscendProofRouteImport } from './routes/ascend.proof'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AscendReaderRoute = AscendReaderRouteImport.update({
  id: '/ascend/reader',
  path: '/ascend/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const AscendProofRoute = AscendProofRouteImport.update({
  id: '/ascend/proof',
  path: '/ascend/proof',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ascend/proof': typeof AscendProofRoute
  '/ascend/reader': typeof AscendReaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ascend/proof': typeof AscendProofRoute
  '/ascend/reader': typeof AscendReaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ascend/proof': typeof AscendProofRoute
  '/ascend/reader': typeof AscendReaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ascend/proof' | '/ascend/reader'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ascend/proof' | '/ascend/reader'
  id: '__root__' | '/' | '/ascend/proof' | '/ascend/reader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AscendProofRoute: typeof AscendProofRoute
  AscendReaderRoute: typeof AscendReaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascend/reader': {
      id: '/ascend/reader'
      path: '/ascend/reader'
      fullPath: '/ascend/reader'
      preLoaderRoute: typeof AscendReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascend/proof': {
      id: '/ascend/proof'
      path: '/ascend/proof'
      fullPath: '/ascend/proof'
      preLoaderRoute: typeof AscendProofRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AscendProofRoute: AscendProofRoute,
  AscendReaderRoute: AscendReaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
