/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AscendProofRouteImport } from './routes/ascend.proof'
import { Route as AscendLibraryRouteImport } from './routes/ascend.library'
import { Route as AscendReaderSlugRouteImport } from './routes/ascend.reader.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AscendProofRoute = AscendProofRouteImport.update({
  id: '/ascend/proof',
  path: '/ascend/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const AscendLibraryRoute = AscendLibraryRouteImport.update({
  id: '/ascend/library',
  path: '/ascend/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AscendReaderSlugRoute = AscendReaderSlugRouteImport.update({
  id: '/ascend/reader/$slug',
  path: '/ascend/reader/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ascend/library': typeof AscendLibraryRoute
  '/ascend/proof': typeof AscendProofRoute
  '/ascend/reader/$slug': typeof AscendReaderSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ascend/library': typeof AscendLibraryRoute
  '/ascend/proof': typeof AscendProofRoute
  '/ascend/reader/$slug': typeof AscendReaderSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ascend/library': typeof AscendLibraryRoute
  '/ascend/proof': typeof AscendProofRoute
  '/ascend/reader/$slug': typeof AscendReaderSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ascend/library' | '/ascend/proof' | '/ascend/reader/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ascend/library' | '/ascend/proof' | '/ascend/reader/$slug'
  id:
    | '__root__'
    | '/'
    | '/ascend/library'
    | '/ascend/proof'
    | '/ascend/reader/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AscendLibraryRoute: typeof AscendLibraryRoute
  AscendProofRoute: typeof AscendProofRoute
  AscendReaderSlugRoute: typeof AscendReaderSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascend/proof': {
      id: '/ascend/proof'
      path: '/ascend/proof'
      fullPath: '/ascend/proof'
      preLoaderRoute: typeof AscendProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascend/library': {
      id: '/ascend/library'
      path: '/ascend/library'
      fullPath: '/ascend/library'
      preLoaderRoute: typeof AscendLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascend/reader/$slug': {
      id: '/ascend/reader/$slug'
      path: '/ascend/reader/$slug'
      fullPath: '/ascend/reader/$slug'
      preLoaderRoute: typeof AscendReaderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AscendLibraryRoute: AscendLibraryRoute,
  AscendProofRoute: AscendProofRoute,
  AscendReaderSlugRoute: AscendReaderSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
