/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAscendPublicationsRouteImport } from './routes/_authenticated/ascend.publications'
import { Route as AuthenticatedAscendProofRouteImport } from './routes/_authenticated/ascend.proof'
import { Route as AuthenticatedAscendLiveRouteImport } from './routes/_authenticated/ascend.live'
import { Route as AuthenticatedAscendLibraryRouteImport } from './routes/_authenticated/ascend.library'
import { Route as ApiPublicRenderPdfRouteImport } from './routes/api/public/render.pdf'
import { Route as ApiPublicRenderKindleRouteImport } from './routes/api/public/render.kindle'
import { Route as ApiPublicRenderCallbackRouteImport } from './routes/api/public/render.callback'
import { Route as AuthenticatedAscendValidateSlugRouteImport } from './routes/_authenticated/ascend.validate.$slug'
import { Route as AuthenticatedAscendReaderSlugRouteImport } from './routes/_authenticated/ascend.reader.$slug'
import { Route as AuthenticatedAscendPublicationsSlugRouteImport } from './routes/_authenticated/ascend.publications.$slug'
import { Route as AuthenticatedAscendPublicationsSlugDistributeRouteImport } from './routes/_authenticated/ascend.publications.$slug.distribute'
import { Route as AuthenticatedAscendPublicationsSlugCommandRouteImport } from './routes/_authenticated/ascend.publications.$slug.command'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAscendPublicationsRoute =
  AuthenticatedAscendPublicationsRouteImport.update({
    id: '/_authenticated/ascend/publications',
    path: '/ascend/publications',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAscendProofRoute =
  AuthenticatedAscendProofRouteImport.update({
    id: '/_authenticated/ascend/proof',
    path: '/ascend/proof',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAscendLiveRoute = AuthenticatedAscendLiveRouteImport.update({
  id: '/_authenticated/ascend/live',
  path: '/ascend/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAscendLibraryRoute =
  AuthenticatedAscendLibraryRouteImport.update({
    id: '/_authenticated/ascend/library',
    path: '/ascend/library',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRenderPdfRoute = ApiPublicRenderPdfRouteImport.update({
  id: '/api/public/render/pdf',
  path: '/api/public/render/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderKindleRoute = ApiPublicRenderKindleRouteImport.update({
  id: '/api/public/render/kindle',
  path: '/api/public/render/kindle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderCallbackRoute = ApiPublicRenderCallbackRouteImport.update({
  id: '/api/public/render/callback',
  path: '/api/public/render/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAscendValidateSlugRoute =
  AuthenticatedAscendValidateSlugRouteImport.update({
    id: '/_authenticated/ascend/validate/$slug',
    path: '/ascend/validate/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAscendReaderSlugRoute =
  AuthenticatedAscendReaderSlugRouteImport.update({
    id: '/_authenticated/ascend/reader/$slug',
    path: '/ascend/reader/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAscendPublicationsSlugRoute =
  AuthenticatedAscendPublicationsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedAscendPublicationsRoute,
  } as any)
const AuthenticatedAscendPublicationsSlugDistributeRoute =
  AuthenticatedAscendPublicationsSlugDistributeRouteImport.update({
    id: '/distribute',
    path: '/distribute',
    getParentRoute: () => AuthenticatedAscendPublicationsSlugRoute,
  } as any)
const AuthenticatedAscendPublicationsSlugCommandRoute =
  AuthenticatedAscendPublicationsSlugCommandRouteImport.update({
    id: '/command',
    path: '/command',
    getParentRoute: () => AuthenticatedAscendPublicationsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ascend/library': typeof AuthenticatedAscendLibraryRoute
  '/ascend/live': typeof AuthenticatedAscendLiveRoute
  '/ascend/proof': typeof AuthenticatedAscendProofRoute
  '/ascend/publications': typeof AuthenticatedAscendPublicationsRouteWithChildren
  '/ascend/publications/$slug': typeof AuthenticatedAscendPublicationsSlugRouteWithChildren
  '/ascend/reader/$slug': typeof AuthenticatedAscendReaderSlugRoute
  '/ascend/validate/$slug': typeof AuthenticatedAscendValidateSlugRoute
  '/api/public/render/callback': typeof ApiPublicRenderCallbackRoute
  '/api/public/render/kindle': typeof ApiPublicRenderKindleRoute
  '/api/public/render/pdf': typeof ApiPublicRenderPdfRoute
  '/ascend/publications/$slug/command': typeof AuthenticatedAscendPublicationsSlugCommandRoute
  '/ascend/publications/$slug/distribute': typeof AuthenticatedAscendPublicationsSlugDistributeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ascend/library': typeof AuthenticatedAscendLibraryRoute
  '/ascend/live': typeof AuthenticatedAscendLiveRoute
  '/ascend/proof': typeof AuthenticatedAscendProofRoute
  '/ascend/publications': typeof AuthenticatedAscendPublicationsRouteWithChildren
  '/ascend/publications/$slug': typeof AuthenticatedAscendPublicationsSlugRouteWithChildren
  '/ascend/reader/$slug': typeof AuthenticatedAscendReaderSlugRoute
  '/ascend/validate/$slug': typeof AuthenticatedAscendValidateSlugRoute
  '/api/public/render/callback': typeof ApiPublicRenderCallbackRoute
  '/api/public/render/kindle': typeof ApiPublicRenderKindleRoute
  '/api/public/render/pdf': typeof ApiPublicRenderPdfRoute
  '/ascend/publications/$slug/command': typeof AuthenticatedAscendPublicationsSlugCommandRoute
  '/ascend/publications/$slug/distribute': typeof AuthenticatedAscendPublicationsSlugDistributeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/ascend/library': typeof AuthenticatedAscendLibraryRoute
  '/_authenticated/ascend/live': typeof AuthenticatedAscendLiveRoute
  '/_authenticated/ascend/proof': typeof AuthenticatedAscendProofRoute
  '/_authenticated/ascend/publications': typeof AuthenticatedAscendPublicationsRouteWithChildren
  '/_authenticated/ascend/publications/$slug': typeof AuthenticatedAscendPublicationsSlugRouteWithChildren
  '/_authenticated/ascend/reader/$slug': typeof AuthenticatedAscendReaderSlugRoute
  '/_authenticated/ascend/validate/$slug': typeof AuthenticatedAscendValidateSlugRoute
  '/api/public/render/callback': typeof ApiPublicRenderCallbackRoute
  '/api/public/render/kindle': typeof ApiPublicRenderKindleRoute
  '/api/public/render/pdf': typeof ApiPublicRenderPdfRoute
  '/_authenticated/ascend/publications/$slug/command': typeof AuthenticatedAscendPublicationsSlugCommandRoute
  '/_authenticated/ascend/publications/$slug/distribute': typeof AuthenticatedAscendPublicationsSlugDistributeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ascend/library'
    | '/ascend/live'
    | '/ascend/proof'
    | '/ascend/publications'
    | '/ascend/publications/$slug'
    | '/ascend/reader/$slug'
    | '/ascend/validate/$slug'
    | '/api/public/render/callback'
    | '/api/public/render/kindle'
    | '/api/public/render/pdf'
    | '/ascend/publications/$slug/command'
    | '/ascend/publications/$slug/distribute'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ascend/library'
    | '/ascend/live'
    | '/ascend/proof'
    | '/ascend/publications'
    | '/ascend/publications/$slug'
    | '/ascend/reader/$slug'
    | '/ascend/validate/$slug'
    | '/api/public/render/callback'
    | '/api/public/render/kindle'
    | '/api/public/render/pdf'
    | '/ascend/publications/$slug/command'
    | '/ascend/publications/$slug/distribute'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/ascend/library'
    | '/_authenticated/ascend/live'
    | '/_authenticated/ascend/proof'
    | '/_authenticated/ascend/publications'
    | '/_authenticated/ascend/publications/$slug'
    | '/_authenticated/ascend/reader/$slug'
    | '/_authenticated/ascend/validate/$slug'
    | '/api/public/render/callback'
    | '/api/public/render/kindle'
    | '/api/public/render/pdf'
    | '/_authenticated/ascend/publications/$slug/command'
    | '/_authenticated/ascend/publications/$slug/distribute'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedAscendLibraryRoute: typeof AuthenticatedAscendLibraryRoute
  AuthenticatedAscendLiveRoute: typeof AuthenticatedAscendLiveRoute
  AuthenticatedAscendProofRoute: typeof AuthenticatedAscendProofRoute
  AuthenticatedAscendPublicationsRoute: typeof AuthenticatedAscendPublicationsRouteWithChildren
  AuthenticatedAscendReaderSlugRoute: typeof AuthenticatedAscendReaderSlugRoute
  AuthenticatedAscendValidateSlugRoute: typeof AuthenticatedAscendValidateSlugRoute
  ApiPublicRenderCallbackRoute: typeof ApiPublicRenderCallbackRoute
  ApiPublicRenderKindleRoute: typeof ApiPublicRenderKindleRoute
  ApiPublicRenderPdfRoute: typeof ApiPublicRenderPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ascend/publications': {
      id: '/_authenticated/ascend/publications'
      path: '/ascend/publications'
      fullPath: '/ascend/publications'
      preLoaderRoute: typeof AuthenticatedAscendPublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ascend/proof': {
      id: '/_authenticated/ascend/proof'
      path: '/ascend/proof'
      fullPath: '/ascend/proof'
      preLoaderRoute: typeof AuthenticatedAscendProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ascend/live': {
      id: '/_authenticated/ascend/live'
      path: '/ascend/live'
      fullPath: '/ascend/live'
      preLoaderRoute: typeof AuthenticatedAscendLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ascend/library': {
      id: '/_authenticated/ascend/library'
      path: '/ascend/library'
      fullPath: '/ascend/library'
      preLoaderRoute: typeof AuthenticatedAscendLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render/pdf': {
      id: '/api/public/render/pdf'
      path: '/api/public/render/pdf'
      fullPath: '/api/public/render/pdf'
      preLoaderRoute: typeof ApiPublicRenderPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render/kindle': {
      id: '/api/public/render/kindle'
      path: '/api/public/render/kindle'
      fullPath: '/api/public/render/kindle'
      preLoaderRoute: typeof ApiPublicRenderKindleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render/callback': {
      id: '/api/public/render/callback'
      path: '/api/public/render/callback'
      fullPath: '/api/public/render/callback'
      preLoaderRoute: typeof ApiPublicRenderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ascend/validate/$slug': {
      id: '/_authenticated/ascend/validate/$slug'
      path: '/ascend/validate/$slug'
      fullPath: '/ascend/validate/$slug'
      preLoaderRoute: typeof AuthenticatedAscendValidateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ascend/reader/$slug': {
      id: '/_authenticated/ascend/reader/$slug'
      path: '/ascend/reader/$slug'
      fullPath: '/ascend/reader/$slug'
      preLoaderRoute: typeof AuthenticatedAscendReaderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ascend/publications/$slug': {
      id: '/_authenticated/ascend/publications/$slug'
      path: '/$slug'
      fullPath: '/ascend/publications/$slug'
      preLoaderRoute: typeof AuthenticatedAscendPublicationsSlugRouteImport
      parentRoute: typeof AuthenticatedAscendPublicationsRoute
    }
    '/_authenticated/ascend/publications/$slug/distribute': {
      id: '/_authenticated/ascend/publications/$slug/distribute'
      path: '/distribute'
      fullPath: '/ascend/publications/$slug/distribute'
      preLoaderRoute: typeof AuthenticatedAscendPublicationsSlugDistributeRouteImport
      parentRoute: typeof AuthenticatedAscendPublicationsSlugRoute
    }
    '/_authenticated/ascend/publications/$slug/command': {
      id: '/_authenticated/ascend/publications/$slug/command'
      path: '/command'
      fullPath: '/ascend/publications/$slug/command'
      preLoaderRoute: typeof AuthenticatedAscendPublicationsSlugCommandRouteImport
      parentRoute: typeof AuthenticatedAscendPublicationsSlugRoute
    }
  }
}

interface AuthenticatedAscendPublicationsSlugRouteChildren {
  AuthenticatedAscendPublicationsSlugCommandRoute: typeof AuthenticatedAscendPublicationsSlugCommandRoute
  AuthenticatedAscendPublicationsSlugDistributeRoute: typeof AuthenticatedAscendPublicationsSlugDistributeRoute
}

const AuthenticatedAscendPublicationsSlugRouteChildren: AuthenticatedAscendPublicationsSlugRouteChildren =
  {
    AuthenticatedAscendPublicationsSlugCommandRoute:
      AuthenticatedAscendPublicationsSlugCommandRoute,
    AuthenticatedAscendPublicationsSlugDistributeRoute:
      AuthenticatedAscendPublicationsSlugDistributeRoute,
  }

const AuthenticatedAscendPublicationsSlugRouteWithChildren =
  AuthenticatedAscendPublicationsSlugRoute._addFileChildren(
    AuthenticatedAscendPublicationsSlugRouteChildren,
  )

interface AuthenticatedAscendPublicationsRouteChildren {
  AuthenticatedAscendPublicationsSlugRoute: typeof AuthenticatedAscendPublicationsSlugRouteWithChildren
}

const AuthenticatedAscendPublicationsRouteChildren: AuthenticatedAscendPublicationsRouteChildren =
  {
    AuthenticatedAscendPublicationsSlugRoute:
      AuthenticatedAscendPublicationsSlugRouteWithChildren,
  }

const AuthenticatedAscendPublicationsRouteWithChildren =
  AuthenticatedAscendPublicationsRoute._addFileChildren(
    AuthenticatedAscendPublicationsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedAscendLibraryRoute: AuthenticatedAscendLibraryRoute,
  AuthenticatedAscendLiveRoute: AuthenticatedAscendLiveRoute,
  AuthenticatedAscendProofRoute: AuthenticatedAscendProofRoute,
  AuthenticatedAscendPublicationsRoute:
    AuthenticatedAscendPublicationsRouteWithChildren,
  AuthenticatedAscendReaderSlugRoute: AuthenticatedAscendReaderSlugRoute,
  AuthenticatedAscendValidateSlugRoute: AuthenticatedAscendValidateSlugRoute,
  ApiPublicRenderCallbackRoute: ApiPublicRenderCallbackRoute,
  ApiPublicRenderKindleRoute: ApiPublicRenderKindleRoute,
  ApiPublicRenderPdfRoute: ApiPublicRenderPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
